import { z } from "zod";

export const ZLoginFormSchema = z.object({
  username: z.string().min(1),
  password: z.string().min(1),
});

export const ZPurchaseReceiveDetailSchema = z.object({
  // PurchaseReceiveDetailId INTEGER PRIMARY KEY,
  PurchaseReceiveId: z.number(),
  FinishedId: z.number(),
  GodownId: z.number(),
  UnitId: z.number(),
  Quantity: z.number(),
  PIndentIssueTranId: z.number(),
  PIndentIssueId: z.number(),
  LotNo: z.string().max(50).nullable(),
  FinishedTypeId: z.number().nullable(),
  QuantityReturn: z.number().nullable(),
  Rate: z.number().nullable(),
  ValueAddedTax: z.number().nullable(),
  CentralSalesTax: z.number().nullable(),
  NetAmount: z.number().nullable(),
  Remark: z.string().max(250).nullable(),
  Penalty: z.number().nullable(),
  ReturnDate: z.string().datetime().nullable(),
  LShortPercentage: z.number().nullable(),
  BaleNumber: z.string().max(50).nullable(),
  BellWeight: z.number().nullable(),
  StateGoodAndServiceTax: z.number().nullable(),
  IntegratedGoodsAndServicesTax: z.number().nullable(),
  BinNumber: z.string().max(50).nullable(),
  VendorLotNumber: z.string().max(50).nullable(),
  PenalityRemarks: z.string().max(250).nullable(),
  OldLotNoWise: z.number().nullable(),
  BillQuantity: z.number().nullable(),
  Particular: z.string().max(50).nullable(),
  TransportBuiltyAmount: z.number().nullable(),
  UnloadingExpenses: z.number().nullable(),
  FiftyMWait: z.number().nullable(),
  YarnShape: z.string().max(20).nullable(),
  Moisture: z.number().nullable(),
  OrderID: z.number().nullable(),
  TCS: z.number().nullable(),
  TagNo: z.string().max(50).nullable(),
  StockUpdateFlag: z.number().nullable(),
  QuantityWeight: z.number().nullable(),
});

export const ZPurchaseReceiveMasterSchema = z.object({
  // PurchaseReceiveId INTEGER PRIMARY KEY,
  CompanyId: z.number(),
  PartyId: z.number(),
  ReceiveNumber: z.string().max(50).nullable(),
  ReceiveDate: z.string().datetime().nullable(),
  UserId: z.number(),
  MasterCompanyId: z.number(),
  GateInNumber: z.string().max(50).nullable(),
  BillNumber: z.string().max(50).nullable(),
  BillNumber1: z.string().max(50).nullable(),
  ChallanStatus: z.number().nullable(),
  MRemark: z.string().max(250).nullable(),
  TransportName: z.string().max(250).nullable(),
  TransportAddress: z.string().max(300).nullable(),
  Driver: z.string().max(100).nullable(),
  VehicleNumber: z.string().max(15).nullable(),
  BiltyNumber: z.string().max(20).nullable(),
  BiltyDate: z.string().datetime().nullable(),
  Freight: z.number().nullable(),
  BillDate: z.string().datetime(),
  OtherCharges: z.number().nullable(),
  LegalVendorId: z.number().nullable(),
  BranchId: z.number().nullable(),
});
